### ISSUE TITLE
smart文件上传那个密码是啥呀

### ISSUE THREAD

**Issue by ewfubwefwe** [yggo/SmartBIAttackTool#4]
文件上传那个密码是啥呀
![image](https://github.com/yggo/SmartBIAttackTool/assets/91933542/782f1eb8-36cd-4366-a16d-fe1f5c78f336)

**Comment by yggo** [comment]
上传按钮下面那么大的空白输入框中粘贴你自己的webshell文件内容，密码由你自己设定。
